// ISO 3166-1 alpha-2 codes for https://github.com/djaiss/mapsicon vector.svg lookups.
// Countries mapped to null have no outline in that repo; England/Scotland/Wales/
// Northern Ireland fall back to the United Kingdom's outline.
export const COUNTRY_ISO_CODES = {
  "Afghanistan": "af", "Albania": "al", "Algeria": "dz", "Andorra": "ad", "Angola": "ao",
  "Antigua and Barbuda": "ag", "Argentina": "ar", "Armenia": "am", "Australia": "au", "Austria": "at",
  "Azerbaijan": "az", "Bahamas": "bs", "Bahrain": "bh", "Bangladesh": "bd", "Barbados": "bb",
  "Belarus": "by", "Belgium": "be", "Belize": "bz", "Benin": "bj", "Bhutan": "bt",
  "Bolivia": "bo", "Bosnia and Herzegovina": "ba", "Botswana": "bw", "Brazil": "br", "Brunei": "bn",
  "Bulgaria": "bg", "Burkina Faso": "bf", "Burundi": "bi", "Cabo Verde": "cv", "Cambodia": "kh",
  "Cameroon": "cm", "Canada": "ca", "Cape Verde": "cv", "Central African Republic": "cf", "Chad": "td",
  "Chile": "cl", "China": "cn", "Colombia": "co", "Comoros": "km",
  "Congo, Democratic Republic of the": "cd", "Congo, Republic of the": "cg", "Costa Rica": "cr",
  "Croatia": "hr", "Cuba": "cu", "Cyprus": "cy", "Czechia": "cz", "Côte d'Ivoire (Ivory Coast)": "ci",
  "Denmark": "dk", "Djibouti": "dj", "Dominica": "dm", "Dominican Republic": "do", "East Timor": "tl",
  "Ecuador": "ec", "Egypt": "eg", "El Salvador": "sv", "England": "gb", "Equatorial Guinea": "gq",
  "Eritrea": "er", "Estonia": "ee", "Eswatini": "sz", "Ethiopia": "et",
  "Federated States of Micronesia": null, "Fiji": "fj", "Finland": "fi", "France": "fr",
  "Gabon": "ga", "Gambia": "gm", "Georgia": "ge", "Germany": "de", "Ghana": "gh", "Greece": "gr",
  "Grenada": "gd", "Guatemala": "gt", "Guinea": "gn", "Guinea-Bissau": "gw", "Guyana": "gy",
  "Haiti": "ht", "Honduras": "hn", "Hungary": "hu", "Iceland": "is", "India": "in", "Indonesia": "id",
  "Iran": "ir", "Iraq": "iq", "Ireland": "ie", "Israel": "il", "Italy": "it", "Jamaica": "jm",
  "Japan": "jp", "Jordan": "jo", "Kazakhstan": "kz", "Kenya": "ke", "Kiribati": "ki", "Kosovo": null,
  "Kuwait": "kw", "Kyrgyzstan": "kg", "Laos": "la", "Latvia": "lv", "Lebanon": "lb", "Lesotho": "ls",
  "Liberia": "lr", "Libya": "ly", "Liechtenstein": "li", "Lithuania": "lt", "Luxembourg": "lu",
  "Madagascar": "mg", "Malawi": "mw", "Malaysia": "my", "Maldives": "mv", "Mali": "ml", "Malta": "mt",
  "Marshall Islands": null, "Mauritania": "mr", "Mauritius": "mu", "Mexico": "mx", "Moldova": "md",
  "Monaco": "mc", "Mongolia": "mn", "Montenegro": "me", "Morocco": "ma", "Mozambique": "mz",
  "Myanmar": "mm", "Namibia": "na", "Nauru": "nr", "Nepal": "np", "Netherlands": "nl",
  "New Zealand": "nz", "Nicaragua": "ni", "Niger": "ne", "Nigeria": "ng", "North Korea": "kp",
  "North Macedonia": "mk", "Northern Ireland": "gb", "Norway": "no", "Oman": "om", "Pakistan": "pk",
  "Palau": "pw", "Palestine": null, "Panama": "pa", "Papua New Guinea": "pg", "Paraguay": "py",
  "Peru": "pe", "Philippines": "ph", "Poland": "pl", "Portugal": "pt", "Qatar": "qa", "Romania": "ro",
  "Russia": "ru", "Rwanda": "rw", "Saint Kitts and Nevis": "kn", "Saint Lucia": "lc",
  "Saint Vincent and the Grenadines": "vc", "Samoa": "ws", "San Marino": "sm",
  "Sao Tome and Principe": "st", "Saudi Arabia": "sa", "Scotland": "gb", "Senegal": "sn",
  "Serbia": "rs", "Seychelles": "sc", "Sierra Leone": "sl", "Singapore": "sg", "Slovakia": "sk",
  "Slovenia": "si", "Solomon Islands": "sb", "Somalia": "so", "South Africa": "za",
  "South Korea": "kr", "South Sudan": "ss", "Spain": "es", "Sri Lanka": "lk", "Sudan": "sd",
  "Suriname": "sr", "Sweden": "se", "Switzerland": "ch", "Syria": "sy", "Taiwan": "tw",
  "Tajikistan": "tj", "Tanzania": "tz", "Thailand": "th", "Togo": "tg", "Tonga": "to",
  "Trinidad and Tobago": "tt", "Tunisia": "tn", "Turkmenistan": "tm", "Tuvalu": null,
  "Türkiye": "tr", "Uganda": "ug", "Ukraine": "ua", "United Arab Emirates": "ae",
  "United Kingdom": "gb", "United States": "us", "Uruguay": "uy", "Uzbekistan": "uz",
  "Vanuatu": "vu", "Vatican City": "va", "Venezuela": "ve", "Vietnam": "vn", "Wales": "gb",
  "Yemen": "ye", "Zambia": "zm", "Zimbabwe": "zw",
};

// flagcdn.com has no ISO code for these; worldflags.net serves their flags directly
// by name slug at assets/img/flags/{slug}-flag.png. No map/outline exists for these.
export const FALLBACK_FLAG_SLUGS = {
  "Federated States of Micronesia": "micronesia",
  "Kosovo": "kosovo",
  "Marshall Islands": "marshall-islands",
  "Palestine": "palestine",
  "Tuvalu": "tuvalu",
};
